[package]
name = "yu-embedded-client"
description = "Cancellable native document-renderer process client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
yu-assets = { path = "../yu-assets" }
serde_json = "1"

[lints]
workspace = true
